git:
  depth: 3

jobs:
  include:
    - name: iOS tests, stable channel
      os: osx
      osx_image: xcode12.2
      language: objective-c
      script:
        - ./flutter/bin/flutter build ios --release --no-codesign
      env: FLUTTER_VERSION=stable

    - name: Android tests, stable channel
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - build-tools-29.0.2
          - android-29
      script:
        - ./flutter/bin/flutter build appbundle
      env: FLUTTER_VERSION=stable

    - name: iOS tests, beta channel
      os: osx
      osx_image: xcode12.2
      language: objective-c
      script:
        - ./flutter/bin/flutter build ios --release --no-codesign
      env: FLUTTER_VERSION=beta

    - name: Android tests, beta channel
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - build-tools-29.0.2
          - android-29
      script:
        - ./flutter/bin/flutter build appbundle
      env: FLUTTER_VERSION=beta

  allow_failures:
    - env: FLUTTER_VERSION=beta

before_script:
  - cd example/
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - "./flutter/bin/flutter doctor"

cache:
  cocoapods: true
  directories:
    - "$HOME/shared/.pub-cache"

notifications:
  email: junaid.akram@count.ly